# Generated by Django 5.2.3 on 2025-06-21 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', message='Введите номер в формате +998xxxxxxxxx')], verbose_name='Номер телефона'),
        ),
    ]
