# Generated by Django 5.2.3 on 2025-06-21 09:45

import products.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('has_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('phones', 'Phone Parts'), ('tablets', 'Tablet Parts'), ('headphones', 'Headphone Parts'), ('accessories', 'Accessories'), ('smart_watch', 'Smart Watch Parts'), ('smart_ring', 'Smart Ring Parts'), ('other', 'Other Parts'), ('batteries', 'Batteries')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=products.models.product.get_upload_path)),
            ],
        ),
    ]
