# Generated by Django 5.2.3 on 2025-07-31 13:40

import django.db.models.deletion
import products.models.product
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('phones', 'Phone Parts'), ('tablets', 'Tablet Parts'), ('headphones', 'Headphone Parts'), ('accessories', 'Accessories'), ('smart_watch', 'Smart Watch Parts'), ('smart_ring', 'Smart Ring Parts'), ('other', 'Other Parts'), ('batteries', 'Batteries')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=products.models.product.get_upload_path)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
